/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDENTIFICADOR_H_RPCGEN
#define _IDENTIFICADOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define IDENTIFICADORPROG 0x20000001
#define IDENTIFICADORVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETIDDISPOSITIVO 1
extern  int * getiddispositivo_1(void *, CLIENT *);
extern  int * getiddispositivo_1_svc(void *, struct svc_req *);
#define GETIDTESTERCOMUN 2
extern  int * getidtestercomun_1(void *, CLIENT *);
extern  int * getidtestercomun_1_svc(void *, struct svc_req *);
#define GETIDTESTERESPECIAL 3
extern  int * getidtesterespecial_1(void *, CLIENT *);
extern  int * getidtesterespecial_1_svc(void *, struct svc_req *);
#define DESREGISTRARTESTERCOMUN 4
extern  int * desregistrartestercomun_1(int *, CLIENT *);
extern  int * desregistrartestercomun_1_svc(int *, struct svc_req *);
#define DESREGISTRARTESTERESPECIAL 5
extern  int * desregistrartesterespecial_1(int *, CLIENT *);
extern  int * desregistrartesterespecial_1_svc(int *, struct svc_req *);
extern int identificadorprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETIDDISPOSITIVO 1
extern  int * getiddispositivo_1();
extern  int * getiddispositivo_1_svc();
#define GETIDTESTERCOMUN 2
extern  int * getidtestercomun_1();
extern  int * getidtestercomun_1_svc();
#define GETIDTESTERESPECIAL 3
extern  int * getidtesterespecial_1();
extern  int * getidtesterespecial_1_svc();
#define DESREGISTRARTESTERCOMUN 4
extern  int * desregistrartestercomun_1();
extern  int * desregistrartestercomun_1_svc();
#define DESREGISTRARTESTERESPECIAL 5
extern  int * desregistrartesterespecial_1();
extern  int * desregistrartesterespecial_1_svc();
extern int identificadorprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDENTIFICADOR_H_RPCGEN */
